### ISSUE TITLE
Push 4k support?

### ISSUE THREAD

**Issue by ghost** [gyazo/Gyazowin#4]
Noticed app on the website contains 4k support however the code for it is not in the repo; is this repo still being maintained?

Thanks, sam.

**Comment by uiur** [comment]
Well, this repo is still being maintained, but we're currently using a forked version for gyazo.com. that's because many features including 4K support depend on our server. 

Do you host screenshots on your own server by using Gyazo?

Feedbacks and pull requests are always welcome.
