### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by mattn** [gyazo/Gyazowin#5]
I had re-wrote gyazowin in golang just now. I don't have plan to provide binary-packages for this. This is my hobby. However I should write license part in README.md.

https://github.com/mattn/gyagowin

**Comment by uiur** [comment]
In README:

> This software is licensed under the GPL.

So you can do whatever you want under the GPL.

btw, your project looks awesome.

**Comment by mattn** [comment]
Thanks

**Comment by mattn** [comment]
ちなみに、ラバーバンドを出す部分だけライブラリコマンドとして切り出したいと思っているのですが、そういった場合はどのようなライセンス形態にすれば良いでしょうか。

**Comment by uiur** [comment]
@mattn 
GPLであればOKだと思っています。
もしもGPLで問題があるので他のオープンソースライセンスを使いたい場合は連絡いただけると、対応はできるかと思います。

**Comment by mattn** [comment]
メインループを回す必要があり、ライブラリとして切り出すには難しいかもしれませんが、もしうまくいった場合 golang は現状バイナリでリンクするしか方法が無い為、リンクするすべての物が GPL になってしまいます。
